const fs = require('fs');
const path = require('path');

const DB_PATH = path.join(__dirname, '..', 'data');
const JOBS_FILE = path.join(DB_PATH, 'jobs.json');
const APPLICATIONS_FILE = path.join(DB_PATH, 'applications.json');

if (!fs.existsSync(DB_PATH)) fs.mkdirSync(DB_PATH, { recursive: true });

function initFile(fp, def = []) { if (!fs.existsSync(fp)) fs.writeFileSync(fp, JSON.stringify(def, null, 2)); }
function readData(fp) { initFile(fp); return JSON.parse(fs.readFileSync(fp, 'utf-8')); }
function writeData(fp, data) { fs.writeFileSync(fp, JSON.stringify(data, null, 2)); }

function seedJobs() {
  const jobs = readData(JOBS_FILE);
  if (jobs.length > 0) return;
  const seedData = [
    { id:"job_001",title:"Email Marketing",company:"Revolut",location:"Madrid, Spain",category:"Marketing",type:"Full Time",description:"Revolut is looking for an Email Marketing specialist to help team manage and optimize email campaigns. You will work closely with the marketing team to develop strategies that increase engagement and conversion rates.\n\nResponsibilities:\n- Design and execute email marketing campaigns\n- Analyze campaign performance and optimize\n- Manage email lists and segmentation\n- Collaborate with design team for email templates\n- A/B test subject lines, content, and send times\n\nRequirements:\n- 2+ years experience in email marketing\n- Proficiency with email marketing platforms\n- Strong analytical skills\n- Excellent written communication",tags:["Marketing","Design"],logo:"R",logoColor:"#FF6B6B",created_at:"2025-02-20T10:00:00Z"},
    { id:"job_002",title:"Brand Designer",company:"Dropbox",location:"San Francisco, US",category:"Design",type:"Full Time",description:"Dropbox is looking for a Brand Designer to help the team create compelling visual identities and maintain brand consistency across all touchpoints.\n\nResponsibilities:\n- Create brand assets and visual guidelines\n- Design marketing collateral\n- Collaborate with product design team\n- Present design concepts to stakeholders\n\nRequirements:\n- 3+ years of brand design experience\n- Expert in Adobe Creative Suite and Figma\n- Strong portfolio showcasing brand work\n- Understanding of typography and color theory",tags:["Design","Business"],logo:"D",logoColor:"#0061FF",created_at:"2025-02-19T10:00:00Z"},
    { id:"job_003",title:"Email Marketing",company:"Pitch",location:"Berlin, Germany",category:"Marketing",type:"Full Time",description:"Pitch is looking for a Customer Manager to join the marketing team and manage email communication strategies.\n\nResponsibilities:\n- Develop and manage email marketing campaigns\n- Track and report on email performance metrics\n- Implement automation workflows\n\nRequirements:\n- 2+ years in email marketing\n- Experience with marketing automation tools\n- Strong analytical and problem-solving skills",tags:["Marketing"],logo:"P",logoColor:"#73AF00",created_at:"2025-02-18T10:00:00Z"},
    { id:"job_004",title:"Visual Designer",company:"Blinkist",location:"Granada, Spain",category:"Design",type:"Full Time",description:"Blinkist is looking for a talented Visual Designer to help design compelling user experiences.\n\nResponsibilities:\n- Create visually stunning designs for web and mobile\n- Develop UI components and design systems\n- Collaborate with UX researchers\n\nRequirements:\n- 3+ years of visual/UI design experience\n- Proficiency in Figma and Adobe Creative Suite\n- Strong understanding of design principles",tags:["Design"],logo:"B",logoColor:"#00C6AE",created_at:"2025-02-17T10:00:00Z"},
    { id:"job_005",title:"Product Designer",company:"ClassPass",location:"Manchester, UK",category:"Design",type:"Full Time",description:"ClassPass is looking for a Product Designer to help us create amazing fitness experiences.\n\nResponsibilities:\n- Design user-centered product features\n- Conduct user research and usability testing\n- Create wireframes, prototypes, and high-fidelity mockups\n\nRequirements:\n- 4+ years of product design experience\n- Expert in Figma\n- Experience with user research methods",tags:["Marketing","Design"],logo:"C",logoColor:"#8B5CF6",created_at:"2025-02-16T10:00:00Z"},
    { id:"job_006",title:"Lead Designer",company:"Canva",location:"Ontario, Canada",category:"Design",type:"Full Time",description:"Canva is looking for a Lead Designer to help develop new features and improve the platform.\n\nResponsibilities:\n- Lead design projects from concept to delivery\n- Mentor junior designers\n- Define design strategy and vision\n\nRequirements:\n- 5+ years of design experience with 2+ in leadership\n- Expert in design tools\n- Strong strategic thinking abilities",tags:["Design","Business"],logo:"Ca",logoColor:"#00C4CC",created_at:"2025-02-15T10:00:00Z"},
    { id:"job_007",title:"Brand Strategist",company:"GoDaddy",location:"Marseille, France",category:"Marketing",type:"Full Time",description:"GoDaddy is looking for a Brand Strategist to join the team and develop brand positioning.\n\nResponsibilities:\n- Develop brand strategies and positioning\n- Conduct market research and competitor analysis\n- Create brand guidelines\n\nRequirements:\n- 4+ years in brand strategy\n- Strong analytical and creative thinking\n- Excellent presentation skills",tags:["Marketing"],logo:"G",logoColor:"#1BDBDB",created_at:"2025-02-14T10:00:00Z"},
    { id:"job_008",title:"Data Analyst",company:"Twitter",location:"San Diego, US",category:"Technology",type:"Full Time",description:"Twitter is looking for a Data Analyst to help derive insights from platform data.\n\nResponsibilities:\n- Analyze large datasets to identify trends\n- Build dashboards and reports\n- Define and track key metrics\n\nRequirements:\n- 3+ years of data analysis experience\n- Proficiency in SQL, Python, and R\n- Experience with visualization tools",tags:["Technology"],logo:"T",logoColor:"#1DA1F2",created_at:"2025-02-13T10:00:00Z"},
    { id:"job_009",title:"Social Media Assistant",company:"Nomad",location:"Paris, France",category:"Marketing",type:"Full Time",description:"Nomad is looking for a Social Media Assistant to manage social presence.\n\nResponsibilities:\n- Create and schedule social media content\n- Monitor social media channels\n- Track social media analytics\n\nRequirements:\n- 1+ year of social media experience\n- Knowledge of major social platforms\n- Strong writing skills",tags:["Full-Time","Marketing","Design"],logo:"N",logoColor:"#FF6550",created_at:"2025-02-12T10:00:00Z"},
    { id:"job_010",title:"Brand Designer",company:"Maze",location:"San Francisco, USA",category:"Design",type:"Full Time",description:"Maze is looking for a Brand Designer to evolve our visual identity.\n\nResponsibilities:\n- Design brand materials and assets\n- Create illustrations and graphics\n- Develop brand guidelines\n\nRequirements:\n- 3+ years of brand design experience\n- Expert in Figma and illustration tools\n- Strong typography skills",tags:["Full-Time","Marketing","Design"],logo:"M",logoColor:"#4353FF",created_at:"2025-02-11T10:00:00Z"},
    { id:"job_011",title:"Interactive Developer",company:"Terraform",location:"Hamburg, Germany",category:"Engineering",type:"Full Time",description:"Terraform is looking for an Interactive Developer to build engaging web experiences.\n\nResponsibilities:\n- Develop interactive web applications\n- Create animations and transitions\n- Build reusable component libraries\n\nRequirements:\n- 3+ years of frontend development\n- Expert in JavaScript, HTML5, CSS3\n- Experience with WebGL or Three.js",tags:["Full-Time","Marketing","Design"],logo:"Tf",logoColor:"#7B61FF",created_at:"2025-02-10T10:00:00Z"},
    { id:"job_012",title:"HR Manager",company:"Packer",location:"Lucern, Switzerland",category:"Human Resource",type:"Full Time",description:"Packer is looking for an HR Manager to lead people operations.\n\nResponsibilities:\n- Manage recruitment and onboarding\n- Develop HR policies\n- Handle employee relations\n\nRequirements:\n- 5+ years of HR management experience\n- Knowledge of employment law\n- Strong interpersonal skills",tags:["Full-Time","Marketing","Management"],logo:"Pk",logoColor:"#FF4444",created_at:"2025-02-09T10:00:00Z"},
    { id:"job_013",title:"Social Media Assistant",company:"Netlify",location:"Paris, France",category:"Marketing",type:"Full Time",description:"Netlify is looking for a Social Media Assistant to help grow our developer community.\n\nResponsibilities:\n- Manage social media accounts\n- Create developer-focused content\n- Track and report on social metrics\n\nRequirements:\n- 1+ year of social media experience\n- Understanding of developer ecosystem\n- Strong writing skills",tags:["Full-Time","Marketing"],logo:"Nt",logoColor:"#00C7B7",created_at:"2025-02-08T10:00:00Z"},
    { id:"job_014",title:"Interactive Developer",company:"Udacity",location:"Hamburg, Germany",category:"Engineering",type:"Full Time",description:"Udacity is looking for an Interactive Developer to build educational experiences.\n\nResponsibilities:\n- Develop interactive learning modules\n- Create engaging web applications\n- Build and maintain component libraries\n\nRequirements:\n- 3+ years of frontend development\n- Expert in React and modern JavaScript\n- Understanding of UX principles",tags:["Full-Time","Marketing","Design"],logo:"U",logoColor:"#02B3E4",created_at:"2025-02-07T10:00:00Z"},
    { id:"job_015",title:"HR Manager",company:"Webflow",location:"Lucern, Switzerland",category:"Human Resource",type:"Full Time",description:"Webflow is looking for an HR Manager to build a world-class team.\n\nResponsibilities:\n- Lead talent acquisition strategy\n- Develop employee engagement programs\n- Manage performance review processes\n\nRequirements:\n- 5+ years in HR management\n- Experience in tech industry\n- Strong leadership skills",tags:["Full-Time","Marketing","Design"],logo:"W",logoColor:"#4353FF",created_at:"2025-02-06T10:00:00Z"},
    { id:"job_016",title:"Software Engineer",company:"Google",location:"Mountain View, US",category:"Engineering",type:"Full Time",description:"Google is looking for a Software Engineer to join the cloud team.\n\nResponsibilities:\n- Design and develop scalable systems\n- Write clean, efficient code\n- Participate in code reviews\n\nRequirements:\n- 3+ years of software engineering experience\n- Proficiency in Java, Python, or Go\n- Experience with distributed systems",tags:["Engineering","Technology"],logo:"Go",logoColor:"#4285F4",created_at:"2025-02-05T10:00:00Z"},
    { id:"job_017",title:"Financial Analyst",company:"Goldman Sachs",location:"New York, US",category:"Finance",type:"Full Time",description:"Goldman Sachs is seeking a Financial Analyst.\n\nResponsibilities:\n- Build financial models and valuations\n- Prepare pitch books and presentations\n- Conduct industry research\n\nRequirements:\n- 2+ years of financial analysis experience\n- Expert in Excel and financial modeling\n- CFA Level 1 or higher preferred",tags:["Finance","Business"],logo:"GS",logoColor:"#7399C6",created_at:"2025-02-04T10:00:00Z"},
    { id:"job_018",title:"Sales Manager",company:"Salesforce",location:"London, UK",category:"Sales",type:"Full Time",description:"Salesforce is looking for a Sales Manager to lead enterprise sales.\n\nResponsibilities:\n- Manage and grow enterprise accounts\n- Lead a team of account executives\n- Develop sales strategies\n\nRequirements:\n- 5+ years of B2B sales experience\n- 2+ years in sales leadership\n- Proven track record of exceeding quota",tags:["Sales","Business"],logo:"SF",logoColor:"#00A1E0",created_at:"2025-02-03T10:00:00Z"}
  ];
  writeData(JOBS_FILE, seedData);
  console.log(`Seeded ${seedData.length} jobs`);
}

initFile(JOBS_FILE); initFile(APPLICATIONS_FILE); seedJobs();
module.exports = { JOBS_FILE, APPLICATIONS_FILE, readData, writeData };
